# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('codigo_de_barras', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
