# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField(default=0)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'PROTEINAS'), (2, 'OXIDOS'), (3, 'QUEMADORES'), (4, 'GANADORES'), (5, 'CREATINAS'), (6, 'GLUTAMINAS'), (7, 'CARNITINAS'), (8, 'CLS'), (9, 'PRECURSORES'), (10, 'MULTIVITAMINICOS'), (11, 'ACCESORIOS'), (12, 'BCCAS'), (13, 'AMINOACIDOS')])),
                ('dec', models.TextField(blank=True, null=True)),
                ('codigo_de_barras', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='accounts.Articulo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
