# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PROTEINAS'), (2, 'OXIDOS')], null=True),
        ),
    ]
