# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_articulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PROTEINAS'), (2, 'OXIDOS'), (3, 'QUEMADORES'), (4, 'GANADORES'), (5, 'CREATINAS'), (6, 'GLUTAMINAS'), (7, 'CARNITINAS'), (8, 'CLS'), (9, 'PRECURSORES'), (10, 'MULTIVITAMINICOS'), (11, 'ACCESORIOS'), (12, 'BCCAS'), (13, 'AMINOACIDOS')], null=True),
        ),
    ]
