# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_articulo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
