# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170708_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='dec',
            field=models.TextField(blank=True),
        ),
    ]
