# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170708_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='accounts.Articulo')),
            ],
        ),
    ]
