# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20170712_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PROTEINAS'), (2, 'OXIDOS'), (3, 'QUEMADORES'), (4, 'GANADORES'), (5, 'CREATINAS'), (6, 'GLUTAMINAS'), (7, 'CARNITINAS'), (8, 'CLS'), (9, 'PRECURSORES'), (10, 'MULTIVITAMINICOS'), (11, 'ACCESORIOS'), (12, 'BCCAS'), (13, 'AMINOACIDOS')], default=1),
            preserve_default=False,
        ),
    ]
